# set up zfs packackes on system

# TODO: include version specific tasks per filename and with_first_found

#- include_tasks: zfs_windows.yml
#  when: ansible_os_family == "Windows"

- include_tasks: zfs_redhat.yml
  when: >
    (ansible_os_family == "RedHat" or ansible_os_family == "AlmaLinux") and
    (ansible_distribution_major_version|int > 7)

#- include_tasks: zfs_debian_9.yml
#  when: ansible_distribution == "Debian" and ansible_distribution_major_version > 8

#- include_tasks: zfs_macos.yml
#  when: ansible_os_family == "Darwin"

# then continue to manage zfs things

# - include_tasks: zfs_manage.yml
